'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Comentario
    Public Property Id As Integer
    Public Property Id_Post As Integer
    Public Property Texto As String
    Public Property Fecha As Nullable(Of Date)

    Public Overridable Property Post As Post

End Class
