'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Post
    Public Property Id As Integer
    Public Property Canal As String
    Public Property Texto As String
    Public Property Img As String
    Public Property Fecha As Nullable(Of Date)
    Public Property idPost As String

    Public Overridable Property Comentario As ICollection(Of Comentario) = New HashSet(Of Comentario)

End Class
