'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class TestEntitiesDB
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=TestEntitiesDB")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Comentario() As DbSet(Of Comentario)
    Public Property Post() As DbSet(Of Post)
    Public Property database_firewall_rules() As DbSet(Of database_firewall_rules)

End Class
